### ISSUE TITLE
post_photo method in upload.py is not working

### ISSUE THREAD

**Issue by vascostmr** [ping/instagram_private_api#215] opened 2019-11-20 16:56 UTC
- [x] Updated to the lastest version v1.6.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Describe the Bug/Error:
The post_photo method on upload.py stopped working since yesterday. And now the response is always  "HTTP Error 400: Bad Request". I tried different accounts and got the same error. So I think I'm not flagged but the Instagram API changed. Did it change or is it just me?

( ``python -V``: Python 3.6.8 )

Code:
```python
from instagram_private_api import Client, ClientCompatPatch, MediaRatios
from instagram_private_api_extensions import media

user_name = 'XXXXXXX'
password = 'XXXXXXX!'

api = Client(user_name, password)

photo_data, photo_size = media.prepare_image('ig.png', aspect_ratios=MediaRatios.standard)
api.post_photo(photo_data, photo_size, caption='Hello World!')
```

Stacktrace:
```
$python3 main.py
~/blog/my_py3/lib/python3.6/site-packages/instagram_private_api/endpoints/upload.py:397: UserWarning: This endpoint has not been fully tested.
  warnings.warn('This endpoint has not been fully tested.', UserWarning)
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "~/blog/my_py3/lib/python3.6/site-packages/instagram_private_api/endpoints/upload.py", line 446, in post_photo
    response = self.opener.open(req, timeout=self.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    api.post_photo(photo_data, photo_size, caption='Hello World!')
  File "~/blog/my_py3/lib/python3.6/site-packages/instagram_private_api/endpoints/upload.py", line 453, in post_photo
    ErrorHandler.process(e, error_response)
  File "~/blog/my_py3/lib/python3.6/site-packages/instagram_private_api/errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Bad Request

```

**Comment by William04A** [comment] 2019-11-20 19:14
To confirm: this happens to me as well.

**Comment by luizolimpio** [comment] 2019-11-20 19:34
Está acontecendo o mesmo aqui.
The same is happening here.

**Comment by iloveautomation** [comment] 2019-11-21 13:18
Same error as a few weeks ago. Hopefully will get fixed soon from IG

**Comment by trocotronic** [comment] 2019-12-14 23:46
Also to me. e400 bad request.

**Comment by ping** [comment] 2019-12-16 08:34
Duplicate of #211

**Closed as completed by ping** 2019-12-16 08:34 UTC
Labels: duplicate
