### ISSUE TITLE
Any effect to this library from newly released api changes on instagram?

### ISSUE THREAD

**Issue by ilkerceng** [ping/instagram_private_api#65] opened 2018-04-07 17:38 UTC
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Do not post screenshots of error messages or code.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x] no spaces).
- Use the *Preview* tab to see how your issue will actually look like.
- Issues about reverse engineering is out of scope and will be closed without response.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version v1.5.0
- [x] Read the [README](https://github.com/ping/instagram_private_api/blob/master/README.md) and [docs](https://instagram-private-api.readthedocs.io/en/latest/)
- [x] [Searched](https://github.com/ping/instagram_private_api/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/ping/instagram_private_api/tree/master/tests) and [examples](https://github.com/ping/instagram_private_api/tree/master/examples)

### Which client are you using?
- [x] app (``instagram_private_api/``)
- [ ] web (``instagram_web_api/``)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.
---
There is a [changelog](https://www.instagram.com/developer/changelog/) released newly. Will this library be affected from these changes? Thanks in advance.

**Comment by notcammy** [comment] 2018-04-07 17:41
See #52

**Comment by ilkerceng** [comment] 2018-04-07 17:56
Yeah, i have seen your post #52  before opening this issue. Is the new changelog also has the same condition with your post?

**Comment by notcammy** [comment] 2018-04-07 18:01
I would guess so since Ping said the public API and private API are unrelated.

**Comment by ilkerceng** [comment] 2018-04-07 18:06
@notcammy Is there any documentation about the difference between public and private api? I got so confused.

**Comment by notcammy** [comment] 2018-04-07 18:07
Not that I know of, and I doubt there is.

**Comment by ping** [comment] 2018-04-08 00:14
This is a duplicate of #52. Even if you don't understand, this is stupid simple to test. The changelog says those endpoints are deprecated, but does it still work in this library? If it does, then you have your answer.

**Closed by ping** 2018-04-08 00:14 UTC
Labels: duplicate
